name = "MacroProg"
uuid = "216f2928-c9f7-4aa6-b3fa-11fbeab08aaf"
version = "0.1.0"
authors = ["Jincheng <golden.baozi123@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
BenchmarkTools = "1.6.3"
CSV = "0.10.15"
DataFrames = "1.8.1"
Distributions = "0.25.122"
ForwardDiff = "1.3.0"
GLM = "1.9.0"
Interpolations = "0.16.2"
LinearAlgebra = "1.12.0"
Logging = "1.11.0"
NLsolve = "4.5.1"
NonlinearSolve = "4.12.0"
OhMyREPL = "0.5.32"
Optim = "1.13.2"
Parameters = "0.12.3"
Plots = "1.41.1"
QuantEcon = "0.17.0"
Random = "1.11.0"
Revise = "3.12.1"
Roots = "2.2.10"
SparseArrays = "1.12.0"
StatsBase = "0.34.8"
StatsPlots = "0.15.8"
